apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paladin-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://lfdt-paladin.github.io/paladin'
    chart: paladin-operator-crd
    targetRevision: 0.1.0 # Replace with the desired chart version
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: paladin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
