apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/italoag/onchain-dev-stack'
    path: firefly/argocd
    targetRevision: main
    helm:
      valueFiles:
        - values/multiparty-arm64.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly # Namespace onde o Firefly será implantado
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
