config:
  debugEnabled: true
  adminEnabled: true
  metricsEnabled: true
  preInit: false
  multipartyEnabled: true
  defaultBlockchainType: ethereum

  # URLs públicas para que o FireFly retorne endpoints HTTPS corretos
  httpPublicUrl: "https://firefly.cluster.eita.cloud"
  adminPublicUrl: "https://firefly.cluster.eita.cloud"

  organizationName: "italo"
  organizationKey: "0x75a99473917701038e854ef6999c76cd947c9f9e"
  
  fireflyContractAddress: "0xDEdB3f6382B73129Ad3f72AD737F348b44Ffc749"
  fireflyContractFirstEvent: 0
  fireflyContracts:
    - address: "0xDEdB3f6382B73129Ad3f72AD737F348b44Ffc749"
      firstEvent: 0

  evmconnectUrl: "http://firefly-evmconnect:5000"
  
  # Configurações do ethconnect - valores corretos conforme template
  ethconnectTopic: "0"
  ethconnectPrefixShort: "fly"
  ethconnectPrefixLong: "firefly"
  ethconnectRetry: true
  
  # Configurações de timeout para evitar problemas de registro
  httpRequestTimeout: 600s
  httpRequestMaxTimeout: 600s
  
  postgresUrl: "postgres://postgres:Bigode%231404%21@postgres-postgresql.database.svc:5432/firefly?sslmode=disable"
  postgresAutomigrate: true

  ipfsApiUrl: "http://ipfs-ipfs.firefly.svc:5001"
  ipfsGatewayUrl: "http://ipfs-ipfs.firefly.svc:8080"

  addresssResolverUrlTemplate: "http://address-resolver.firefly-os/wallets/{{.Key}}"

core:
  nodeNameOverride: "italo-node"
  image:
    repository: ghcr.io/italoag/firefly
    tag: "latest-arm64"
    pullPolicy: IfNotPresent
  
  nodeSelector:
    kubernetes.io/arch: arm64
  
  metrics:
    serviceMonitor:
      enabled: true
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 6
  initContainers: |
      - name: wait-for-dx
        image: busybox:1.36.1
        command: ['sh', '-c', 'until nc -z firefly-dx 5000; do echo waiting for dx; sleep 2; done;']
      - name: create-database
        image: postgres:15
        command: ['sh', '-c']
        args:
          - |
            DB_NAME="firefly"
            USER_NAME="postgres"
            PSQL_SERVER="postgres://postgres:Bigode%231404%21@postgres-postgresql.database.svc:5432/postgres?sslmode=disable"
            PSQL_URL="postgres://postgres:Bigode%231404%21@postgres-postgresql.database.svc:5432/firefly?sslmode=disable"
            
            echo "Waiting for PostgreSQL server..."
            until psql "${PSQL_SERVER}" -c "SELECT 1;" > /dev/null 2>&1; do
              echo "PostgreSQL not ready, waiting..."
              sleep 2
            done
            
            echo "Checking if database exists..."
            if ! psql "${PSQL_SERVER}" -c "SELECT datname FROM pg_database WHERE datname = '${DB_NAME}';" | grep -q "${DB_NAME}"; then
              echo "Database '${DB_NAME}' does not exist; creating."
              psql "${PSQL_SERVER}" -c "CREATE DATABASE \"${DB_NAME}\" WITH OWNER \"${USER_NAME}\";"
            else
              echo "Database '${DB_NAME}' already exists."
            fi
            
            echo "Waiting for database to be available..."
            until psql "${PSQL_URL}" -c "SELECT 1;" > /dev/null 2>&1; do
              echo "Database not ready, waiting..."
              sleep 2
            done
            echo "Database is ready!"
  
  jobs:
    postgresMigrations:
      enabled: false
    registration:
      enabled: true
      ffUrl: "http://firefly:5000"
      ffNamespaces:
        - default

dataexchange:
  enabled: true
  image:
    repository: ghcr.io/italoag/firefly-dataexchange-https
    tag: "latest-arm64"
    pullPolicy: Always
  certificate:
    enabled: true
    issuerRef:
      kind: ClusterIssuer
      name: selfsigned-ca
  tlsSecret:
    enabled: false

# Sandbox habilitado
sandbox:
  enabled: true
  image:
    repository: ghcr.io/italoag/firefly-sandbox
    tag: "latest-arm64"
    pullPolicy: Always
  nodeSelector:
    kubernetes.io/arch: arm64

signer:
  enabled: true

evmconnect:
  enabled: true
  image:
    repository: ghcr.io/italoag/firefly-evmconnect
    tag: "latest-arm64"
    pullPolicy: Always
  nodeSelector:
    kubernetes.io/arch: arm64
  config:
    jsonRpcUrl: "http://firefly-signer.firefly.svc:8545"
    policyEngine: |
      policyengine.simple:
        fixedGasPrice: "0"
        resubmitInterval: 5m
        gasOracle:
          mode: fixed

erc1155:
  enabled: true
  image:
    repository: ghcr.io/italoag/firefly-tokens-erc1155
    tag: "latest-arm64"
    pullPolicy: Always
  
  nodeSelector:
    kubernetes.io/arch: arm64
  
  config:
    ethconnectTopic: "erc1155"

erc20erc721:
  enabled: true
  image:
    repository: ghcr.io/italoag/firefly-tokens-erc20-erc721
    tag: "latest-arm64"
    pullPolicy: Always
  
  nodeSelector:
    kubernetes.io/arch: arm64
  
  config:
    ethconnectTopic: "erc20erc721"